run:
  mode: 'train'
  device: 'gpu'
transforms: none
dataset:
  class_name: "ISIC2018Dataset"
  input_size: 224
  training:
    params:
      data_dir: "data/ISIC2018/ISIC2018_Task1-2_Training_Input"
  validation:
    params:
      data_dir: "data/ISIC2018/ISIC2018_Task1_Training_GroundTruth"
  number_classes: 2
data_loader:
  train: 
    batch_size: 16
    shuffle: true
    num_workers: 8
    pin_memory: true
  validation: 
    batch_size: 16
    shuffle: false
    num_workers: 8
    pin_memory: true
  test:
    batch_size: 16
    shuffle: false
    num_workers: 4
    pin_memory: false
training:
  optimizer:
    name: 'Adam'
    params:
      lr: 0.0001
  criterion:
    name: "DiceLoss"
    params: {}
  scheduler:
    factor: 0.5
    patience: 10
  epochs: 100
model:
  save_dir: './saved_models/isic2018_unet'
  save_name: 'isic2018_unet.pth'
  load_weights: false
  name: 'UNet'
  params:
    in_channels: 3
    out_channels: 2
    with_bn: false

# preprocess: